export const adminCompanies = [
  {
    id: "studio-leaf",
    name: "스튜디오 리프",
    accountName: "브랜드 A",
    manager: "김민서",
    contact: "leaf@example.com",
    status: "활성",
    pendingOrders: 2,
    activeOrders: 3,
    completedOrders: 18,
  },
  {
    id: "perfume-atelier",
    name: "퍼퓸 아틀리에",
    accountName: "브랜드 B",
    manager: "박지훈",
    contact: "scent@example.com",
    status: "활성",
    pendingOrders: 1,
    activeOrders: 4,
    completedOrders: 24,
  },
  {
    id: "garden-biome",
    name: "가든 바이옴",
    accountName: "브랜드 C",
    manager: "이서연",
    contact: "garden@example.com",
    status: "검토",
    pendingOrders: 0,
    activeOrders: 1,
    completedOrders: 12,
  },
];

export const companyOrders = [
  {
    id: "ORD-2026-0512",
    companyId: "studio-leaf",
    campaign: "비건 세럼 리뷰",
    status: "승인 대기",
    payment: "입금 확인 필요",
    amount: 379500,
    requestedAt: "2026-04-26",
    stopRequested: false,
  },
  {
    id: "ORD-2026-0510",
    companyId: "studio-leaf",
    campaign: "수분 진정 키워드",
    status: "결제 대기",
    payment: "계좌 안내 완료",
    amount: 253000,
    requestedAt: "2026-04-25",
    stopRequested: false,
  },
  {
    id: "ORD-2026-0511",
    companyId: "perfume-atelier",
    campaign: "니치 향수 리뷰",
    status: "진행중",
    payment: "포인트 차감 완료",
    amount: 561000,
    requestedAt: "2026-04-25",
    stopRequested: true,
  },
  {
    id: "ORD-2026-0509",
    companyId: "garden-biome",
    campaign: "유기농 식단",
    status: "완료",
    payment: "포인트 차감 완료",
    amount: 814000,
    requestedAt: "2026-04-18",
    stopRequested: false,
  },
];

export const companyProgressItems = [
  {
    id: "WRK-001",
    companyId: "studio-leaf",
    orderId: "ORD-2026-0512",
    title: "비건 세럼 리뷰",
    status: "승인 대기",
    completed: 0,
    total: 8,
    blogs: [],
  },
  {
    id: "WRK-002",
    companyId: "perfume-atelier",
    orderId: "ORD-2026-0511",
    title: "니치 향수 리뷰",
    status: "진행중",
    completed: 6,
    total: 10,
    blogs: ["lune-note", "city-aroma", "daily-scent"],
  },
  {
    id: "WRK-003",
    companyId: "garden-biome",
    orderId: "ORD-2026-0509",
    title: "유기농 식단",
    status: "완료",
    completed: 12,
    total: 12,
    blogs: ["green-log", "plant-canvas", "weekend-herb"],
  },
];
